name: ARO Store Demo
trigger: none
variables:
  bicepfolder: '$(System.DefaultWorkingDirectory)\bicep'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Bicep Infrastructure
    jobs:
      - job: BicepScan
        displayName: Scan and Run What-If
        pool:
          vmImage: 'windows-latest'
        steps:
        - task: RunARMTTKTests@1
          inputs:
            templatelocation: $(bicepfolder)
            resultLocation: '$(System.DefaultWorkingDirectory)\results'
            includeTests: 'VM Images Should Use Latest Version,Resources Should Have Location'
            skipTests: 'VM Images Should Use Latest Version,Resources Should Have Location'
            mainTemplates: 'template1.json, template2.json'
            allTemplatesMain: false
            cliOutputResults: true
            recurse: true
            ignoreExitCode: false
            usePSCore: true
        
        